<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-44484-1660724887/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet="Earth"
diameter=12742
print('the diameter of{} is {} kilometers.'.format(planet,diameter));

the diameter ofEarth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d={'k1':[1,2,3,{'trichy':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["trichy"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)
print("an array of 10 zeros:")

an array of 10 zeros:


In [6]:
array=np.ones(10)*5
print("an array of 10 fives:")
print(array)

an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
array=np.arange(20,36,2)
print("array of all even integer from 20 to 35")
print(array)

array of all even integer from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,7])
print(a)
print(b)

[1 2 3]
[4 5 7]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [10]:
import pandas as pd
import numpy as np
arrayA=['f','d','g']
arrayB=['1','2','3']
arrayC=[4,5,6]
pd.DataFrame(np.array([arrayA,arrayB,arrayC]),columns=["AA","NN","gg"])

AA NN gg
0  f  d  g
1  1  2  3
2  4  5  6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
import pandas
pandas.date_range(sdate,edate-timedelta(days=1),freq='d')
sdate=date(2023,1,1)
edate=date(2023,2,10)
def dates_bwn_twodates(start_date,end_date):
  for n in range(int ((end_date - start_date).days)):
    yield start_date+timedelta(n)
    print(dates_bwn_twodates(sdate,edate))

NameError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [18]:
import pandas as pd
list=[['aaa',22],['bbb',25],['ccc',24]]
df=pd.DataFrame(list,columns=['Tag','number'])
print(df)


   Tag  number
0  aaa      22
1  bbb      25
2  ccc      24
